-- Textos editables de la plantilla. Cada instalación mantiene una sola fila.
alter table public.site_settings
  add column if not exists home_eyebrow text not null default 'Estamos aquí para ayudarle a encontrar su próximo espacio',
  add column if not exists home_catalog_button text not null default 'Ver todo el catálogo',
  add column if not exists home_contact_button text not null default 'Contactar un asesor',
  add column if not exists home_featured_title text not null default 'Propiedades destacadas',
  add column if not exists home_featured_subtitle text not null default 'Una selección de propiedades disponibles para usted.',
  add column if not exists home_empty_featured text not null default 'Aún no hay propiedades destacadas. Vuelva pronto.',
  add column if not exists home_cta_title text not null default '¿Listo para encontrar su propiedad?',
  add column if not exists home_cta_text text not null default 'Contáctenos y permítanos acompañarle en su próxima decisión inmobiliaria.',
  add column if not exists home_cta_button text not null default 'Contáctenos',
  add column if not exists catalog_title text not null default 'Nuestras propiedades',
  add column if not exists catalog_subtitle text not null default 'Encuentre la propiedad adecuada utilizando nuestros filtros de búsqueda.',
  add column if not exists catalog_empty text not null default 'No se encontraron propiedades con esos criterios.',
  add column if not exists about_eyebrow text not null default 'Sobre nosotros',
  add column if not exists about_title text not null default 'Construimos mejores experiencias inmobiliarias',
  add column if not exists about_mission_title text not null default 'Nuestra misión',
  add column if not exists about_values_title text not null default 'Nuestros valores',
  add column if not exists contact_eyebrow text not null default 'Estamos para ayudarle',
  add column if not exists contact_title text not null default 'Contáctenos y agende una conversación',
  add column if not exists contact_subtitle text not null default 'Nuestro equipo le atenderá para conocer sus necesidades y orientarle.';
